// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM7RxtW7LYcuCovyYzBIOVs8NwtPvmhD8',
    appId: '1:577071377890:web:45f9d032c33a31772b5dbb',
    messagingSenderId: '577071377890',
    projectId: 'instagram-clone3-8ec35',
    authDomain: 'instagram-clone3-8ec35.firebaseapp.com',
    storageBucket: 'instagram-clone3-8ec35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSR-UKtyorGnUBWxVaW_o2IeHKeUuPsg',
    appId: '1:577071377890:android:6f70574094e12be02b5dbb',
    messagingSenderId: '577071377890',
    projectId: 'instagram-clone3-8ec35',
    storageBucket: 'instagram-clone3-8ec35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmb-VuDpip_LrkHBkwubkAqEo_bcpRxD0',
    appId: '1:577071377890:ios:dcafa3a3250c253e2b5dbb',
    messagingSenderId: '577071377890',
    projectId: 'instagram-clone3-8ec35',
    storageBucket: 'instagram-clone3-8ec35.appspot.com',
    iosBundleId: 'com.example.instagramClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmb-VuDpip_LrkHBkwubkAqEo_bcpRxD0',
    appId: '1:577071377890:ios:860cae7f8578e6552b5dbb',
    messagingSenderId: '577071377890',
    projectId: 'instagram-clone3-8ec35',
    storageBucket: 'instagram-clone3-8ec35.appspot.com',
    iosBundleId: 'com.example.instagramClone2.RunnerTests',
  );
}
